### ISSUE TITLE
build.py not working on debian 10

### ISSUE THREAD

**Issue by joachimheintz** [csound-flossmanual/csound-floss#2]
on a clean debian 10 build, i created a venv and had two problems:

1. during pip install -r requirements.txt there is one error message:
Building wheels for collected packages: pyinotify
  Running setup.py bdist_wheel for pyinotify ... error
  Complete output from command /home/jh/src/csound-floss/python-env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kk5h3zp_/pyinotify/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-nhntxr43 --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pyinotify
  Running setup.py clean for pyinotify
Failed to build pyinotify

2. the pip command finished nevertheless, but afterwards pandoc could not be found:
Installing collected packages: PyYAML, grizzled-python, cloudpickle, pyinotify, doit, click, future, shutilwhich, panflute, webencodings, tinycss2, cssselect2, defusedxml, pycparser, cffi, cairocffi, pillow, CairoSVG, Pyphen, six, html5lib, WeasyPrint, tornado, livereload
  Running setup.py install for pyinotify ... done
Successfully installed CairoSVG-2.4.2 PyYAML-5.1.2 Pyphen-0.9.5 WeasyPrint-50 cairocffi-1.1.0 cffi-1.13.2 click-7.0 cloudpickle-1.2.2 cssselect2-0.2.2 defusedxml-0.6.0 doit-0.31.1 future-0.18.2 grizzled-python-2.2.0 html5lib-1.0.1 livereload-2.6.1 panflute-1.11.2 pillow-6.2.1 pycparser-2.19 pyinotify-0.9.6 shutilwhich-1.1.0 six-1.13.0 tinycss2-1.0.2 tornado-6.0.3 webencodings-0.5.1
(python-env) jh@lenovdeb10:~/src/csound-floss$ python3 build.py html
Traceback (most recent call last):
  File "build.py", line 130, in <module>
    PANDOC        = find_in_path("pandoc")
  File "/home/jh/src/csound-floss/lib/__init__.py", line 364, in find_in_path
    raise OSError(f"""Can't find "{command}" in PATH.""")
OSError: Can't find "pandoc" in PATH.

**Comment by hlolli** [comment]
closing because this file isn't there anymore
