### ISSUE TITLE
build.py issue on osx

### ISSUE THREAD

**Issue by joachimheintz** [csound-flossmanual/csound-floss#3]
i followed the description and built all dependencies with
pip install -r requirements.txt

but plantuml is not being found.  i added it to PATH which seems to work ...

(base) fmsbw19s-Mac-Pro:~ fmsbw19$ plantuml.py
-bash: /Users/fmsbw19/anaconda3/lib/python3.7/site-packages/plantuml.py: Permission denied

... but it does not help:
(base) fmsbw19s-Mac-Pro:csound-floss fmsbw19$ python3 build.py html
-- combined_metadata
.  html
/Users/fmsbw19/anaconda3/bin/pandoc -f markdown+line_blocks+escaped_line_breaks+smart+fenced_code_blocks+fenced_code_attributes+backtick_code_blocks+yaml_metadata_block+implicit_figures+tex_math_dollars+implicit_figures+link_attributes +RTS -K4096m -RTS -F scripts/pandoc-filter.py -F scripts/plantuml-filter.py --standalone --mathjax  -t html --css=resources/styles/fonts.css --css=resources/styles/html.css -H resources/html/head_include.html -B resources/html/body_include.html -o csound-floss-export.html tmp/preprocessed/metadata.yaml tmp/preprocessed/00--aa-toc.md tmp/preprocessed/00-a-preface.md tmp/preprocessed
etc ...
[WARNING] Duplicate note reference '1' at line 3414 column 1
etc ...
[WARNING] Duplicate identifier 'introduction' at line 34346 column 1
Traceback (most recent call last):
  File "scripts/plantuml-filter.py", line 24, in <module>
    COMMAND = find_in_path("plantuml")
  File "/Users/fmsbw19/src/csound-floss/lib/__init__.py", line 364, in find_in_path
    raise OSError(f"""Can't find "{command}" in PATH.""")
OSError: Can't find "plantuml" in PATH.
Error running filter scripts/plantuml-filter.py:
fd:13: hPutBuf: resource vanished (Broken pipe)

**Comment by hlolli** [comment]
closing because this file isn't used anymore
