### ISSUE TITLE
add search bar and keyboard navigation

### ISSUE THREAD

**Issue by a1ro** [csound-flossmanual/csound-floss#41]
This is not an issue but rather a suggestion.

What would you think of adding a search bar right below previous/next section in the sidebar?
A somewhat low visibility box similar to the dark mode toggle would fit well with the overall design in my opinion.

If it gets implemented, I'd love to focus search bar at the press of `/` key.
It is standard and allows to navigate content very fast.

And while we're at it, adding keybindings for those previous/next section would complete the set. I don`t know about other keyboard layouts, but with en_US, the bottom-right keys are:

![search_keys](https://user-images.githubusercontent.com/11812395/93630626-4a0ebd00-f9b8-11ea-80a9-c175f537e8a8.png)

So `,` `.` and `/` keys would translate to `<` previous, `>` next and `?` search functions.

**Comment by hlolli** [comment]
I will look into this, if you know of any example of the keybindings, could you send me a link?

I'd probably bind left and right arrow too.

**Comment by A1RO** [comment]
Github itself is an example but I suppose it is closed source.
If you mean a code example, I don't know about Node.js, sorry.

> I'd probably bind left and right arrow too.

Sure, makes a lot of sense, especially when the site switches to mobile view (narrow window on desktop).

And on mobile, left and right _swipes_ would be analogous to left and right _arrows_ on desktop.
It is starting to act like an EPUB viewer at this point. I think that would be a good thing.
