### ISSUE TITLE
example 03F03_Score_Tricks.csd

### ISSUE THREAD

**Issue by zeffii** [csound-flossmanual/csound-floss#49]
As suggested at the start of the manual, it's a good idea to type these examples out by hand to form some sort of muscle memory. I'm a total novice at csound, but the manual is gentle!  

this example `03F03_Score_Tricks.csd ` in the pdf contains a bug ( looks like a escaping issues with ` %%` and `\[` , `\]`

it should look like this

![image](https://user-images.githubusercontent.com/619340/94681078-19694480-0323-11eb-9600-a3e7d36afd7a.png)

but the pdf shows it as

![image](https://user-images.githubusercontent.com/619340/94681126-330a8c00-0323-11eb-8e8e-0854910781f1.png)

A PR/patch for it

https://github.com/csound-flossmanual/csound-floss/pull/50

**Comment by joachimheintz** [comment]
thanks!
@hlolli should we simply remove the backslashes in the markdown source, or are they needed for anything?

**Comment by hlolli** [comment]
These are mistaken leftovers from latex special-char escaping. Yes these should be removed, I will double check there isn't any change in the html output as a result of this patch.
