### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by excalamus** [csound-flossmanual/csound-floss#67]
I see "FLOSS" in the name but cannot locate a COPYING or LICENSE file, nor do I see anything related to Creative Commons.  Under what terms may I use this work?

I often take notes alongside documentation and, aside from understanding how any contribututions may be used by others, I would like to know if I could publish separately should my writings significantly diverge or otherwise be unfit for merging (e.g. different format, etc.).

Regardless, thank you for creating, sharing, and maintaining this excellent resource.

**Comment by joachimheintz** [comment]
you are right; thanks for pointing to it.  yes, the csound floss manual was always meant to be used anywhere with reference to the source.  as long as we developed this book under flossmanuals.net the license was done more or less automatically.  for this new version we have chosen CC-BY for the book content and a software license for the programming part.  we will add these licences now.

if you have any more questions please let me know here, or to my private email.

  joachim

**Comment by excalamus** [comment]
Wonderful, thank you.
