### ISSUE TITLE
Manual Ex. 03E02_i_k_arrays.csd

### ISSUE THREAD

**Issue by ST-Music** [csound-flossmanual/csound-floss#88]
Hi again, I just started studying arrays. I think this example needs to be updated as the array opcode is deprecated and I received an error message so it would not run. It appears to be a matter of changing opcode array to fillarray.

Ex. from manual ver 7.0.1
instr 1
iArr[] array 1, 2, 3 
IArr[0] = iArr[0] + 10
prints " iArr[0] = %d\n\n", iArr[0] 
endin

After reading Canonical I modified to:

instr 1
iArr[] fillarray 1, 2, 3
iArr[0] = iArr[0] + 10
prints "   iArr[0] = %d\n\n", iArr[0]
endin

instr 2
kArr[] fillarray 1, 2, 3
kArr[0] = kArr[0] + 10
printks "   kArr[0] = %d\n", 0, kArr[0]
endin

This worked for me with no error mssg.

**Comment by joachimheintz** [comment]
yes this is a leftover from the old convention.  corrected now in https://github.com/csound-flossmanual/csound-floss/blob/develop/book/03-e-arrays.md
thanks!
